# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyTest Automation API

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  # Job to set up Python, install dependencies, and run the tests
  test:
    runs-on: ubuntu-latest  # Can be changed to windows-latest or macos-latest if needed

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # You can use a specific version like '3.9' or '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 4: Set environment variables (in case you need to set them in the pipeline)
    - name: Set Environment Variables
      run: |
        echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}" >> $GITHUB_ENV
        echo "API_PORTAL=${{ secrets.API_PORTAL }}" >> $GITHUB_ENV
        echo "API_IDEKU=${{ secrets.API_IDEKU }}" >> $GITHUB_ENV
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        echo "API_POS=${{ secrets.API_POS }}" >> $GITHUB_ENV
        echo "BASE_URL=${{ vars.BASE_URL }}" >> $GITHUB_ENV
        echo "ENV=${{ vars.ENV }}" >> $GITHUB_ENV
      # Ensure the SLACK_WEBHOOK is added in your GitHub secrets.

    # Step 5: Run tests
    - name: Run tests
      run: |
        pytest -s -v --json-report --json-report-file=report.json  # Run pytest and generate json report || exit 0

    # Step 6: Send notification to Slack (run your Python script)
    - name: Send notification to Slack
      run: |
        python helpers/report_generator.py  # Make sure the Python script is in your repository
