# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyTest Automation API

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  # Job to set up Python, install dependencies, and run the tests
  test:
    runs-on: ubuntu-latest  # Can be changed to windows-latest or macos-latest if needed

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # You can use a specific version like '3.9' or '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 5: Set environment variables (in case you need to set them in the pipeline)
    - name: Set Environment Variables
      run: |
        echo "MATTERMOST_WEBHOOK=${{ secrets.MATTERMOST_WEBHOOK }}" >> $GITHUB_ENV
        echo "MATTERMOST_WEBHOOK=${{ vars.ENV }}" >> $GITHUB_ENV
      # Ensure the MATTERMOST_WEBHOOK is added in your GitHub secrets.

    # Step 4: Run tests
    - name: Run tests
      run: |
        pytest -v --json-report --json-report-file=report.json  # Run pytest and generate json report

    # Step 6: Send notification to Mattermost (run your Python script)
    - name: Send notification to Mattermost
      run: |
        python helper/summary_helper.py  # Make sure the Python script is in your repository

    # Optionally, you can clean up logs or artifacts after running tests
    - name: Upload test results (optional)
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: result.log
